finish responsive
AMichalMurawski/goit-markup-project-group3 pull request #36
Opened 2022-10-14 20:48 UTC by jnosowska

2022-10-14 21:52 UTC, lukasikgrzegorz requested changes
Wszystko ok, poza main.css i main.min umawialiśmy się, że ich niw rzucamy :) Racja?

2022-10-14 21:59 UTC, jnosowska commented
nie zauwazyłam ze sie zaciagnely jak brala commita ;(

2022-10-14 22:15 UTC, lukasikgrzegorz approved these changes

2022-10-15 08:44 UTC, michamas reviewed
to moje pierwsze sprawdzenie, więc daj znać czy zbyt lub za mało dokładne;)

2022-10-15 08:44 UTC, michamas commented on src/sass/components/_advantages.scss
> +    min-width: 230px;
dałbym max-width 230px, zeby text zawijał się na "vulputate"

2022-10-15 08:44 UTC, michamas commented on src/sass/components/_advantages.scss
>      height: 156px;
height: 100%? bo inaczej jak wrap zaczyna działać (przy 768px) ikona serca nachodzi na górne elementy listy

//EDIT: chociaż właściwie w tablecie szerokość <li> powinna być max 180px (a img i text 100% (chyba wtedy zadziała?)), wtedy te 3 pozycje są obok siebie.

2022-10-15 08:44 UTC, michamas commented on src/sass/components/_advantages.scss
> +      @include font-type(bold, text-normal, medium, small);
dla PC text powinien byc szerszy z kolei: 330px.
(mam na myśli wszystkie elementy listy, więc jeżeli img masz ogarniczone to tam trzeba rozszerzyć do 330px)

2022-10-15 08:44 UTC, michamas commented on src/sass/main.css
>  .advantages {
usuwamy te pliki main.css i main.css.map w końcu? bo zam chyba zapomniałem w swoim commicie;)

2022-10-15 08:54 UTC, jnosowska commented on src/sass/main.css
>  .advantages {
samo mi wskoczylo ja tez nie zauwazylam tego kompletnie a jzu nie mialam jak cofnac ( musialam w trakcie pracy wcisnac watch sass...)

2022-10-15 10:56 UTC, jnosowska commented on src/sass/components/_advantages.scss
> +    min-width: 230px;
poprawione

2022-10-15 10:57 UTC, jnosowska commented on src/sass/components/_advantages.scss
>      height: 156px;
ale szerokosc czy wysokosc bo nie koniecznie rozumiem wypowiedz? :)

2022-10-15 16:45 UTC, AMichalMurawski submitted a review, later dismissed

2022-10-15 16:46 UTC, AMichalMurawski approved these changes

2022-10-15 16:46 UTC, merged