modal + location
AMichalMurawski/goit-markup-project-group3 pull request #49
Opened 2022-10-15 19:45 UTC by michamas

nie perfect, ale dziś już nic nie wymyśle

2022-10-15 20:07 UTC, lukasikgrzegorz requested changes
![image](https://user-images.githubusercontent.com/71289836/196005490-0fa72778-09ce-4a15-81f2-9c230671f6c6.png)
Kwestie wizualne :) Przewodnim motywem na stornie są zaokrąglone boki na wszystkich elementach.  Tak więc tutaj dałbym jakiś border radius, żeby zachować wizualną spójność. Co Ty na to?? 

Do modala możemy dać jednego JS. Bo skrypt robi dokładnie to samo, nie ma sensu go dublować, ale to już moja kwestia :) 


Zmień te ramki i będzie super jak dla mnie! Dobra robota.

2022-10-16 15:09 UTC, lukasikgrzegorz approved these changes
po poprawkach działa

2022-10-16 16:05 UTC, lukasikgrzegorz approved these changes
ok

2022-10-16 17:04 UTC, lukasikgrzegorz submitted a review, later dismissed
ok

2022-10-16 17:22 UTC, AMichalMurawski approved these changes

2022-10-16 17:22 UTC, merged